### ISSUE TITLE
The training time or epochs for  fb1k5237 and wn18nn

### ISSUE THREAD

**Issue by quqxui** [chenchens190009/CSProm-KG#2]
Hi, thanks for your great work. I want to know how many gpu hours or epochs you need to get the reported results of fb1k5237 and wn18nn on your paper?

**Comment by chenchens190009** [comment]
Hi @quqxui, 

Thank you for your interest. wn18rr is a relatively smaller dataset and a bit hard to converge, so we use the default epoch value, which is 500. For fb15k237, epoch is configured as 60, as specified in the main page of this repo.
