### ISSUE TITLE
Unable to load checkpoint file（FB15K-237）

### ISSUE THREAD

**Issue by gyf6666** [chenchens190009/CSProm-KG#5]
Dear author, can you help me with this issue, I can't load the fb15k-237 checkpoint you provided
![image](https://github.com/chenchens190009/CSProm-KG/assets/148872612/6e938344-ca28-4616-8b80-d0d073719b98)

**Comment by gyf6666** [comment]
This seems to be caused by dimension inconsistency, but the source code has strict=False already set, and I still don't know how to fix it

**Comment by 13082672037** [comment]
RuntimeError: Error(s) in loading state_dict for KGCPromptTuner:
        size mismatch for graph_model.fc.weight: copying a param with shape torch.Size([144, 21600]) from checkpoint, the shape in current model is torch.Size([144, 25200]).
我也出现类似的问题了，请问最后怎么解决的

**Comment by gyf6666** [comment]
@13082672037 This is due to the inconsistency between the dimension of your current model and the dimension of the checkpoint. You can use the checkpoint generated by the current model to test, rather than directly using the checkpoint provided by the author.
